url: https://libertysowl.github.io/freelancer-theme/
baseurl: /freelancer-theme/

# Site settings
title: Good Words
email: goodwordsonlinel@gmail.com
description: "Freelance translation, proofreading and copy-writing services."


# Team names, titles and social links
people:
- name: Cecilia Fernandez-Juno
  pic: 1
  position: Trlanslator, proof-reader and copy-writer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Hatch End, Middlesex
  - line: United Kingdom

# Build settings
markdown: kramdown
permalink: pretty
